- src/concrete/erc1155/FlowERC1155.sol
- src/concrete/erc721/FlowERC721.sol
The motivation behind this change is to correct the structure to successfully pass the fmt test.
The structure was corrected in specific contracts (FlowERC721 and FlowERC1155).
> 2024-07-24-fmt-updated-structure

- test/abstract/InterpreterMockTest.sol
- test/abstract/TestConstants.sol
To provide testing using a mock interpreter.
A mock interpreter has been implemented.
> Added abstract mock interpreter and constants

- test/abstract/FlowAbstractTest.sol
- test/abstract/FlowUtilsAbstractTest.sol
To ensure the testing process for flow, abstract utilities are needed.
Implemented auxiliary functionality for stack filling and receipts filtering.
> Added utilities for testing flow

- test/abstract/FlowERC20Test.sol
- test/concrete/flowErc20/FlowConstructionInitializeTest.sol
- test/concrete/flowErc20/FlowErc20ConstructionInitializeTest.sol
#58 
Move deprecated "flowErc20 construction init" test
> 2024 08 08 58 porting legacy tests from flowerc20construction

- test/concrete/flowBasic/FlowConstructionTest.sol
#81 
Move deprecated "flow construction init"  test
> 2024 08 08 29 porting legacy tests from flow construction

- src/concrete/erc721/FlowERC721.sol
- test/abstract/FlowERC721Test.sol
- test/concrete/flowErc20/FlowConstructionInitializeTest.sol
- test/concrete/flowErc721/FlowConstructionInitializeTest.sol
#81
https://github.com/rainlanguage/rain.flow/issues/143
Move deprecated "FlowERC721 construction init" test
> FlowERC721 Construction InitializeTest

- test/concrete/flowBasic/FlowTest.sol
Move deprecated "Flow ERC1155 To ERC1155Test construction init" test
> 2024 08 11 flow erc1155 to erc1155 test

- test/concrete/flowBasic/FlowTest.sol
Move deprecated "flow erc721 to erc721" test
> 2024 08 11 flow erc721 to erc721 test

- test/concrete/flowBasic/FlowTest.sol
Move deprecated "flow erc20 to erc20" test
> 2024 08 11 flow erc20 to erc20 test

- test/concrete/flowErc1155/FlowTest.sol
Porting legacy tests from flowerc1155flow  test case should flow for erc20 erc721 on the good path
Create new foundry test
> 115 porting erc20 erc721 

- test/abstract/FlowBasicTest.sol
- test/abstract/FlowUtilsAbstractTest.sol
- test/abstract/InterpreterMockTest.sol
- test/concrete/flowBasic/FlowMulticallTest.sol
Move deprecated "Multicall Flows" test
> 2024-08-14 Flow Basic Multicall Flows Test

- test/concrete/flowBasic/FlowSignedContextTest.sol
Move deprecated " flow basic validate signed contexts test" test
> 2024 08 13 flow basic validate signed contexts test

- test/concrete/flowBasic/FlowSignedContextTest.sol
Move deprecated "Validate Multiple SignedContexts" test
> 2024 08 13 flow basic  validate multiple signedContexts Test

- test/concrete/flowBasic/FlowTimeTest.sol
Move deprecated " flow basic storage save data" test
> 2024 08 13 flow basic time test

- test/concrete/flowErc20/FlowTest.sol
Porting flowerc20flow should flow for erc20 <> erc20
Add new test in foundry
> Add testFlowERC20FlowERC20ToERC20

- test/abstract/FlowERC20Test.sol
- test/abstract/FlowERC721Test.sol
contracts in */abstract/* should be abstract contracts
Make contracts abstract 
> Make contracts abstract

- test/abstract/FlowBasicTest.sol
- test/concrete/flowBasic/FlowMulticallTest.sol
- test/concrete/flowBasic/FlowPreviewTest.sol
- test/concrete/flowBasic/FlowTest.sol
- test/concrete/flowErc1155/FlowTest.sol
- test/concrete/flowErc20/FlowTest.sol
Move deprecated "preview defined flow io for erc1155 multi element arrays" test
> 2024 08 15 preview defined flow io for erc1155 multi element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview defined flow io for erc721 multi element arrays" test
> 2024 08 15 preview defined flow io for erc721 multi element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview defined flow io for erc20 multi element arrays" test
> 2024 08 16 preview defined flow io for erc20 multi element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview defined flow io for erc1155 single element arrays" test
> 2024 08 16 preview defined flow io for erc1155 single element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview defined flow io for erc721 single element arrays" test
> 2024 08 16 preview defined flow io for erc721 single element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview defined flow io for erc20 single element arrays" test
> 2024 08 16 preview defined flow io for erc20 single element arrays test

- test/concrete/flowBasic/FlowPreviewTest.sol
Move deprecated "preview empty flow io" test
> 2024 08 16 preview empty flow io test

- test/abstract/InterpreterMockTest.sol
- test/concrete/flowBasic/FlowContextTest.sol
- test/lib/ContextBuilder.sol
Move deprecated "fshould register and load flow times into context (throttle flow output amount)" test.
Moved and adapted deprecated  test.
>  Tests context handling during interpreter call

- test/abstract/FlowERC20Test.sol
- test/abstract/FlowERC721Test.sol
- test/concrete/flowErc20/FlowTest.sol
- test/concrete/flowErc721/FlowConstructionInitializeTest.sol
- test/concrete/flowErc721/FlowTest.sol
Porting legacy tests from ".FlowERC721/flow" — test case "should flow for erc20<->erc721
Porting legacy tests from ".FlowERC721/flow" — test case "should flow for ERC1155<->ERC1155
Add new foundry test
> Porting legacy tests from ".FlowERC721/flow" — test case "should flow for erc20<->erc721

- test/concrete/flowBasic/FlowExpressionTest.sol
Move deprecated "Flow basic should deploy expression" test.
Moved and adapted deprecated test.
> 2024 08 19 flow basic should deploy expression test

- test/concrete/flowBasic/FlowExpressionTest.sol
Move deprecated "Should validate context from event" test.
Moved and adapted deprecated test.
> 2024 08 24 should validate context from event test

- test/abstract/FlowUtilsAbstractTest.sol
- test/concrete/flowBasic/FlowContextTest.sol
- test/concrete/flowBasic/FlowExpressionTest.sol
- test/concrete/flowBasic/FlowMulticallTest.sol
- test/concrete/flowBasic/FlowPreviewTest.sol
- test/concrete/flowBasic/FlowSignedContextTest.sol
- test/concrete/flowBasic/FlowTest.sol
- test/concrete/flowBasic/FlowTimeTest.sol
- test/concrete/flowErc1155/FlowSignedContextTest.sol
- test/concrete/flowErc1155/FlowTest.sol
- test/concrete/flowErc1155/FlowTimeTest.sol
- test/concrete/flowErc20/FlowSignedContextTest.sol
- test/concrete/flowErc20/FlowTest.sol
- test/concrete/flowErc721/FlowTest.sol
Improve code readability.
The stack generator has been updated to use the structures `FlowERC1155IOV1`, `FlowERC721IOV1`, and `FlowERC20IOV1`.
> Updated flow utils  generate flow stack

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated "flow erc20 preview defined flow io for erc1155 multi element arrays" test
> 2024 08 22 flow erc20 preview defined flow io for erc1155 multi element arrays test

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated "flow erc20 preview defined flow io for erc721 multi element arrays" test
> 2024 08 23 flow erc20 preview defined flow io for erc721 multi element arrays test

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated "flow erc20 preview defined flow io for erc1155 single element arrays" test
> 2024 08 23 flow erc20 preview defined flow io for erc1155 single element arrays test

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated " flow erc20 base preview defined flow io for erc721 single element arrays " test
> 2024 08 23 flow erc20 base preview defined flow io for erc721 single element arrays test

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated "flow erc20 preview defined flow io for erc20 single element arrays" test
> 2024 08 23 flow erc20 preview defined flow io for erc20 single element arrays test

- test/concrete/flowErc20/FlowPreviewTest.sol
Move deprecated " flow erc20 preview empty flow io" test.
Moved deprecated test.
> 2024 08 23 flow erc20 preview empty flow io test

- test/concrete/flowBasic/FlowConstructionTest.sol
- test/concrete/flowBasic/FlowContextTest.sol
- test/concrete/flowBasic/FlowExpressionTest.sol
- test/concrete/flowBasic/FlowMulticallTest.sol
- test/concrete/flowBasic/FlowPreviewTest.sol
- test/concrete/flowBasic/FlowSignedContextTest.sol
- test/concrete/flowBasic/FlowTest.sol
- test/concrete/flowBasic/FlowTimeTest.sol
- test/concrete/flowErc1155/FlowSignedContextTest.sol
- test/concrete/flowErc1155/FlowTest.sol
- test/concrete/flowErc1155/FlowTimeTest.sol
- test/concrete/flowErc20/FlowConstructionInitializeTest.sol
- test/concrete/flowErc20/FlowMulticallTest.sol
- test/concrete/flowErc20/FlowPreviewTest.sol
- test/concrete/flowErc20/FlowSignedContextTest.sol
- test/concrete/flowErc20/FlowTest.sol
- test/concrete/flowErc20/FlowTimeTest.sol
- test/concrete/flowErc721/FlowConstructionInitializeTest.sol
- test/concrete/flowErc721/FlowTest.sol
- test/concrete/flowErc721/FlowTimeTest.sol
pragmas need to be pinned to a specific version like =0.8.x for concrete contracts, including tests
Update pragma to specific version
> Update pragma version to concrete test files

- test/abstract/FlowERC721Test.sol
- test/concrete/flowErc721/FlowMulticallTest.sol
Porting legacy tests from ".FlowERC721/multicall" — test case "should call multiple flows from same flow contract at once using multicall"
Add new test in foundry
> Flowerc721multicall  test case should call multiple flows from same flow contract at once using multicall

- test/concrete/flowErc721/FlowSignedContextTest.sol
Porting legacy tests from ".FlowERC721/signedContext" — test case "should validate multiple signed contexts
Porting legacy tests from ".FlowERC721/signedContext" — test case "should validate a signed context"
Add new tests in foundry
> should validate signed contexts

- test/abstract/FlowERC20Test.sol
- test/abstract/FlowUtilsAbstractTest.sol
- test/abstract/InterpreterMockTest.sol
- test/concrete/flowErc20/FlowMulticallTest.sol
- test/concrete/flowErc20/FlowTest.sol
- test/lib/ContextBuilder.sol
Move deprecated "Flow erc20 flow erc721 to erc1155" test
> 2024-08-29 Flow erc20 flow erc721 to erc1155 test

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview defined flow io for erc1155 multi element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc1155 multi element arrays test

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview defined flow io for erc721 multi element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc721 multi element arrays test

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated " flow erc721 preview defined flow io for erc20 multi element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc20 multi element arrays test

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview defined flow io for erc1155 single element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc1155 single element arrays

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview defined flow io for erc721 single element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc721 single element arrays

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview defined flow io for erc20 single element arrays" test
> 2024 09 02 flow erc721 preview defined flow io for erc20 single element arrays test

- test/concrete/flowErc721/FlowPreviewTest.sol
Move deprecated "flow erc721 preview empty flow io test" test
> 2024 09 02 flow erc721 preview empty flow io test

- test/abstract/FlowBasicTest.sol
- test/abstract/FlowERC20Test.sol
- test/abstract/FlowERC721Test.sol
- test/concrete/flowErc721/FlowExpressionTest.sol
- test/concrete/flowErc721/FlowMulticallTest.sol
- test/concrete/flowErc721/FlowTest.sol
Move deprecated "Flow ERC721 Supports Transfer Preflight Hook" test
> 024-09-03 Flow ERC721 Supports Transfer Preflight Hook

- test/concrete/flowErc1155/FlowTest.sol
Porting legacy tests from flowerc1155flow  test case should mint and burn tokens per flow in exchange for another token eg erc20
Add new test in foundry
> 113 porting legacy tests from flowerc1155flow  test case should mint and burn tokens per flow in exchange for another token eg erc20

- test/concrete/flowErc20/FlowTest.sol
Porting legacy tests from ".FlowERC20/flow" — test case "should not flow if number of sentinels is less than MIN_FLOW_SENTINELS"
Add test in foundry
> WIP add testFlowERC20MinFlowSentinel

- test/concrete/flowErc1155/FlowTest.sol
Porting legacy tests from ".FlowERC1155/flow" — test case "should not flow if number of sentinels is less than MIN_FLOW_SENTINELS"
Add new test in foundry
> Add test testFlowERC1155MinFlowSentinel

- test/concrete/flowBasic/FlowContextTest.sol
- test/concrete/flowBasic/FlowExpressionTest.sol
- test/concrete/flowBasic/FlowMulticallTest.sol
- test/concrete/flowBasic/FlowSignedContextTest.sol
- test/concrete/flowBasic/FlowTest.sol
- test/concrete/flowBasic/FlowTimeTest.sol
- test/concrete/flowErc1155/Erc1155FlowTest.sol
- test/concrete/flowErc1155/FlowExpressionTest.sol
- test/concrete/flowErc1155/FlowMulticallTest.sol
- test/concrete/flowErc1155/FlowSignedContextTest.sol
- test/concrete/flowErc1155/FlowTimeTest.sol
- test/concrete/flowErc20/Erc20FlowTest.sol
- test/concrete/flowErc20/FlowExpressionTest.sol
- test/concrete/flowErc20/FlowMulticallTest.sol
- test/concrete/flowErc20/FlowSignedContextTest.sol
- test/concrete/flowErc20/FlowTimeTest.sol
- test/concrete/flowErc721/Erc721FlowTest.sol
- test/concrete/flowErc721/FlowExpressionTest.sol
- test/concrete/flowErc721/FlowMulticallTest.sol
- test/concrete/flowErc721/FlowSignedContextTest.sol
- test/concrete/flowErc721/FlowTimeTest.sol
The repetitive code in test cases complicated maintenance and understanding of the tests. There was a need to optimize the code structure for better readability and to reduce duplication.
Added new class FlowTransferOperation was added, where basic token transfer operations are implemented, improving the modularity and reusability of the code.
> 2024 09 30 integration transfer operation
